name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    # Runs at 00:00AM UTC
    - cron: '0 0 * * *'

jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest
    steps:
      - uses: waslost0/waka-readme-stats@master #PLEASE USE MASTER BRANCH
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_PROJECTS: "False"
          SHOW_LOC_CHART : "False"
          SHOW_LINES_OF_CODE: "True"
          LOCALE: "en"
          SHOW_LANGUAGE: "True"
          INPUT_COMMIT_BY_ME: "True"
          SHOW_PROFILE_VIEWS: "False"
          INPUT_PUSH_BRANCH_NAME: "master"
          
